"""
Enrich pub_names.csv with FPI (Fucked Pub Index) scores using local VOA data.

Reads /tmp/voa/pub-risk.json (generated by build_pub_risk.py) which contains
all pubs with their 2023/2026 rateable values and raw % change.

Matches pubs by postcode area + fuzzy name matching, then computes a
FPI score (0-100) using the official piecewise scale and assigns a category.

Output: Updates pub_names.csv with columns: fpi_score, fpi_category,
        fpi_pct_change, voa_name

Usage:
    python add_fpi_scores.py

    Requires /tmp/voa/pub-risk.json from build_pub_risk.py.
    Falls back to fpi_lookup.csv if the JSON is not available.
"""

import csv
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
PUB_NAMES_CSV = SCRIPT_DIR / "pub_names.csv"
FPI_LOOKUP_CSV = SCRIPT_DIR / "fpi_lookup.csv"
VOA_JSON = Path("/tmp/voa/pub-risk.json")

# FPI score → category thresholds (from ismypubfucked.com)
CATEGORIES = [
    (10, "somehow fine"),
    (30, "feeling it"),
    (60, "struggling"),
    (90, "fucked"),
    (101, "absolutely fucked"),
]


def get_category(score):
    for threshold, cat in CATEGORIES:
        if score < threshold:
            return cat
    return "absolutely fucked"


def pct_change_to_fpi(pct):
    """Convert a % change to an FPI score (0-100) using the official scale.

    Piecewise linear mapping:
      0-10%   -> FPI  0-10
      10-50%  -> FPI 10-30
      50-100% -> FPI 30-60
      100-200% -> FPI 60-90
      >200%   -> FPI 90-100
    """
    if pct < 0:
        return 0
    # (pct_low, pct_high, fpi_low, fpi_high)
    segments = [
        (0, 10, 0, 10),
        (10, 50, 10, 30),
        (50, 100, 30, 60),
        (100, 200, 60, 90),
        (200, 500, 90, 100),
    ]
    for pct_lo, pct_hi, fpi_lo, fpi_hi in segments:
        if pct <= pct_hi:
            t = (pct - pct_lo) / (pct_hi - pct_lo)
            return round(fpi_lo + t * (fpi_hi - fpi_lo))
    return 100


def normalise_name(name):
    """Normalise a pub name for matching."""
    name = name.upper().strip()
    # Remove common prefixes
    for prefix in ["THE ", "YE OLDE ", "YE "]:
        if name.startswith(prefix):
            name = name[len(prefix):]
    # Normalise ampersands
    name = name.replace("&", "AND").replace("'", "").replace("'", "")
    # Remove punctuation and extra spaces
    name = re.sub(r"[^\w\s]", "", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name


def extract_pub_name_from_voa(voa_name):
    """Extract the pub name from a VOA address string.

    VOA names look like:
      "THE CAT AND MUTTON, 76, BROADWAY MARKET, LONDON"
      "PRINCE OF WALES, 48, CLEAVER SQUARE, LONDON"
    The pub name is typically the first comma-separated part.
    """
    parts = voa_name.split(",")
    return parts[0].strip()


def postcode_area(postcode):
    """Extract area from a full postcode: 'E8 4QJ' -> 'E8', 'EC1A 2BB' -> 'EC1'."""
    postcode = postcode.strip().upper()
    # Match the area part: letters followed by digits (e.g., E8, EC1, SW1, WC2)
    m = re.match(r"([A-Z]{1,2}\d{1,2})", postcode)
    return m.group(1) if m else postcode.split()[0] if postcode else ""


def load_voa_data():
    """Load VOA pub-risk.json and index by postcode area."""
    print(f"Loading {VOA_JSON} ...")
    with open(VOA_JSON) as f:
        pubs = json.load(f)
    print(f"  Loaded {len(pubs)} pubs")

    # Index by postcode area for fast lookup
    by_area = {}
    for pub in pubs:
        area = postcode_area(pub["postcode"])
        if area:
            by_area.setdefault(area, []).append(pub)

    return pubs, by_area


def get_candidates(postcode_area_code, by_area):
    """Get VOA candidates for a postcode area, expanding short codes.

    If 'EC' has no direct matches, expand to EC1, EC2, EC3, EC4 etc.
    Similarly 'W' expands to W1, W2, ... W14, 'SW' to SW1..SW20.
    """
    candidates = by_area.get(postcode_area_code, [])
    if candidates:
        return candidates

    # Try expanding: 'EC' -> 'EC1', 'EC2', etc.
    all_candidates = []
    prefix = postcode_area_code.upper()
    for area_key in by_area:
        if area_key.startswith(prefix) and area_key != prefix:
            all_candidates.extend(by_area[area_key])
    return all_candidates


def extract_street(location):
    """Extract street name from location like 'Broadway Market, London'."""
    if not location:
        return ""
    # Take the part before the first comma (the street/area name)
    street = location.split(",")[0].strip()
    return street.upper()


def name_in_voa_address(target, voa_full_address):
    """Check if pub name appears anywhere in VOA address (not just first part).

    Handles cases like 'GRD FLR 7 CHAPEL PLACE 320, OLD STREET'
    where the pub name isn't the first comma-separated part.
    """
    norm_address = normalise_name(voa_full_address)
    return target in norm_address


def find_best_match(pub_name, postcode_area_code, by_area, location=""):
    """Find the best matching VOA pub by name within a postcode area.

    Uses both pub name and street/location to score candidates.
    Scoring: name_match (0-2) + street_match (0-1)
      - name exact match in first part = 2
      - name found anywhere in address = 1
      - street name found in address = 1
    """
    candidates = get_candidates(postcode_area_code, by_area)
    if not candidates:
        return None

    target = normalise_name(pub_name)
    street = extract_street(location)

    best_match = None
    best_score = 0

    for pub in candidates:
        score = 0
        voa_pub_name = extract_pub_name_from_voa(pub["name"])
        norm_voa = normalise_name(voa_pub_name)
        voa_full = pub["name"].upper()

        # Name matching
        if norm_voa == target:
            score += 3  # Perfect name match in first part
        elif target in norm_voa or norm_voa in target:
            score += 2  # Partial name match in first part
        elif name_in_voa_address(target, pub["name"]):
            score += 1  # Name found somewhere in full address

        if score == 0:
            continue

        # Street/location matching (bonus for disambiguation)
        if street and len(street) > 2:
            # Check if street name appears in VOA address
            # e.g., "BROADWAY MARKET" in "THE CAT AND MUTTON, 76, BROADWAY MARKET, LONDON"
            if street in voa_full:
                score += 2
            else:
                # Try individual words from street (at least 4 chars)
                street_words = [w for w in street.split() if len(w) >= 4]
                matches = sum(1 for w in street_words if w in voa_full)
                if matches > 0:
                    score += 1

        if score > best_score:
            best_score = score
            best_match = pub

    # Require at least a name match (score >= 1)
    if best_match and best_score >= 1:
        return best_match

    return None


def load_manual_lookup():
    """Load manually-created FPI lookup CSV as fallback."""
    lookup = {}
    if not FPI_LOOKUP_CSV.exists():
        return lookup
    with open(FPI_LOOKUP_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = normalise_name(row.get("pub_name", ""))
            if name:
                lookup[name] = {
                    "fpi_score": row.get("fpi_score", ""),
                    "fpi_category": row.get("fpi_category", ""),
                }
    return lookup


def main():
    if not PUB_NAMES_CSV.exists():
        print(f"Error: {PUB_NAMES_CSV} not found. Run extract_pub_names.py first.")
        sys.exit(1)

    with open(PUB_NAMES_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        pubs = list(reader)

    if not pubs:
        print("No pubs found in CSV.")
        sys.exit(1)

    print(f"Loaded {len(pubs)} pubs from {PUB_NAMES_CSV}")

    # Try VOA data first
    use_voa = VOA_JSON.exists()
    by_area = {}
    if use_voa:
        all_voa, by_area = load_voa_data()
    else:
        print(f"\n  {VOA_JSON} not found.")
        print(f"  Run build_pub_risk.py first, or use fpi_lookup.csv fallback.\n")

    # Load manual lookup as fallback
    manual_lookup = load_manual_lookup()
    if manual_lookup:
        print(f"  Loaded {len(manual_lookup)} manual entries from {FPI_LOOKUP_CSV}")

    # Enrich each pub
    matched_voa = 0
    matched_manual = 0
    unmatched = []

    for pub in pubs:
        fpi_data = None

        # Try VOA match
        if use_voa:
            area = pub.get("postcode_area", "")
            location = pub.get("location", "")
            match = find_best_match(pub["pub_name"], area, by_area, location)
            if match:
                pct = match["fpi"]  # raw % change from VOA data
                fpi_score = pct_change_to_fpi(pct)
                pub["fpi_score"] = str(fpi_score)
                pub["fpi_category"] = get_category(fpi_score)
                pub["fpi_pct_change"] = str(pct)
                pub["voa_name"] = match["name"]
                matched_voa += 1
                continue

        # Try manual lookup
        norm = normalise_name(pub["pub_name"])
        manual = manual_lookup.get(norm)
        if manual:
            pub["fpi_score"] = manual["fpi_score"]
            pub["fpi_category"] = manual["fpi_category"]
            pub["fpi_pct_change"] = ""
            pub["voa_name"] = ""
            matched_manual += 1
        else:
            pub["fpi_score"] = ""
            pub["fpi_category"] = ""
            pub["fpi_pct_change"] = ""
            pub["voa_name"] = ""
            unmatched.append(pub["pub_name"])

    # Write updated CSV
    fieldnames = [
        "pub_name", "location", "postcode_area", "photo_url",
        "fpi_score", "fpi_category", "fpi_pct_change", "voa_name",
    ]
    with open(PUB_NAMES_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(pubs)

    total_matched = matched_voa + matched_manual
    print(f"\nDone! Matched {total_matched}/{len(pubs)} pubs.")
    if matched_voa:
        print(f"  VOA matches: {matched_voa}")
    if matched_manual:
        print(f"  Manual matches: {matched_manual}")
    if unmatched:
        print(f"  Unmatched: {len(unmatched)}")
        for name in unmatched[:20]:
            print(f"    - {name}")
        if len(unmatched) > 20:
            print(f"    ... and {len(unmatched) - 20} more")

    print(f"\nUpdated {PUB_NAMES_CSV}")

    # Print matched pubs
    if total_matched > 0:
        print(f"\nPubs with FPI scores:")
        print(f"{'Pub Name':<35} {'Score':>5}  {'Category':<17} {'% Change':>8}  VOA Name")
        print("-" * 120)
        for pub in pubs:
            if pub["fpi_score"]:
                print(
                    f"{pub['pub_name']:<35} {pub['fpi_score']:>5}  "
                    f"{pub['fpi_category']:<17} {pub['fpi_pct_change']:>8}  "
                    f"{pub.get('voa_name', '')[:45]}"
                )


if __name__ == "__main__":
    main()
